name: GitHubNuget

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  windows:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.103'
      - name: RunNuke Gihub Push
        run: ./build.sh NuGetPushGithub --GithubToken ${{ secrets.GITHUB_TOKEN }}
