name: GitHubNuget

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
     - 'main'
     
jobs:
  windows:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: RunNuke Gihub Push
        run: ./build.sh NuGetPushGithub --GithubToken ${{ secrets.GITHUB_TOKEN }}
